feature: Adicionar a função de cadastrar e pesquisar um cliente
FIAP-8SOAT-G6/tech-challenge-lanchonete pull request #13
Opened 2024-08-05 22:19 UTC by anadezuo

2024-08-06 02:00 UTC, vitorrafael requested changes

2024-08-06 10:12 UTC, anadezuo commented on src/core/customers/exceptions/MissingPropertyError.js
Então, fiquei pensando nisso. Talvez uma area de commons.
Mas fiquei na dúvida.
Vou investigar um pouco melhor se pode quebrar a arquitetura

2024-08-06 10:16 UTC, anadezuo commented on src/core/customers/entities/Customer.js
> +  }
Pensei em fazer a validação só se der tempo mesmo.

2024-08-06 10:19 UTC, anadezuo commented on src/core/customers/use-cases/CustomerManagement.js
> +    const newCustomer = new Customer({ id: null, name, cpf, email });
Nossa mudei a forma de criar o Customer, e esqueci esse carinha aqui :pray:

2024-08-06 10:21 UTC, anadezuo commented on src/tests/core/customer/use-cases/CustomerManagement.test.js
> +  async function setupRepository() {
Feito :raised_hands:

2024-08-06 10:25 UTC, anadezuo commented on src/tests/core/customer/use-cases/CustomerManagement.test.js
> +      }
Cara eu não  consegui ver o teste quebrar, tipo o primeiro ciclo do TDD? Em que você implementa primeiro teste e depois faz o desenvolvimento?
Eu implementei o teste, e ele passava, sem a implementação do código de erro. Dai arrumei outro jeito, que é esse dai. :disappointed:

2024-08-06 10:30 UTC, anadezuo commented on src/tests/core/customer/use-cases/CustomerManagement.test.js
> +      }
Ah, achei meu erro, esqueci de colocar um await na frente do expect para esperar a validação do erro :face_exhaling:

2024-08-06 22:08 UTC, vitorrafael requested changes

2024-08-06 22:08 UTC, vitorrafael commented on src/adapters/database/FakeCustomerRepository.js
> +  async findByCPF({ cpf }) {
Conforme conversamos, aqui pode ser apenas `cpf` sem destruturação.

2024-08-06 22:08 UTC, vitorrafael commented on src/adapters/database/FakeCustomerRepository.js
> +  async create({ customer }) {
Conforme conversamos, aqui pode ser apenas `customer` sem destruturação.

2024-08-06 22:08 UTC, vitorrafael commented on src/adapters/database/FakeCustomerRepository.js
> +    if (!dbCustomer || dbCustomer?.length === 0) return undefined;
Esse length é necessário para qual cenário? Considerando que sempre teremos apenas um cliente.

2024-08-06 22:08 UTC, vitorrafael commented on src/adapters/database/SequelizeCustomerRepository.js
> +  async create({ customer }) {
Conforme conversamos, aqui pode ser apenas `customer` sem destruturação.

2024-08-06 22:08 UTC, vitorrafael commented on src/adapters/database/SequelizeCustomerRepository.js
> +  async findByCPF({ cpf }) {
Conforme conversamos, aqui pode ser apenas `cpf` sem destruturação.

2024-08-06 22:08 UTC, vitorrafael commented on src/adapters/database/SequelizeCustomerRepository.js
> +    if (!dbCustomer || dbCustomer?.length === 0) return undefined;
Esse length é necessário para qual cenário? Considerando que sempre teremos apenas um customer ou undefined

2024-08-06 22:08 UTC, vitorrafael commented on src/core/customers/exceptions/InvalidCPFError.js
> +  constructor({ cpf }) {
Conforme conversamos, aqui pode ser apenas `cpf` sem destruturação.

2024-08-06 22:08 UTC, vitorrafael commented on src/core/customers/use-cases/CustomerManagement.js
> +  async create({ customer }) {
Conforme conversamos, aqui pode ser apenas `customer` sem destruturação.

2024-08-06 22:08 UTC, vitorrafael commented on src/core/customers/use-cases/CustomerManagement.js
> +  async findByCPF({ cpf }) {
Conforme conversamos, aqui pode ser apenas `cpf` sem destruturação.

2024-08-06 22:08 UTC, vitorrafael commented on src/core/customers/use-cases/CustomerManagement.js
> +  async validateCustomerExistence({ cpf }) {
Conforme conversamos, aqui pode ser apenas `cpf` sem destruturação.

2024-08-06 22:08 UTC, vitorrafael commented on src/tests/core/customer/use-cases/CustomerManagement.test.js
> +      }
Aqui acho que faltou o commit com essa change para `await expect`

2024-08-06 22:08 UTC, vitorrafael commented on src/core/customers/exceptions/ExistentCustomerError.js
> +  }
Conforme conversamos, aqui pode ser apenas `cpf` sem destruturação.

2024-08-06 22:08 UTC, vitorrafael commented on src/core/customers/exceptions/MissingPropertyError.js
> +  }
Conforme conversamos, aqui pode ser apenas `property` sem destruturação.

2024-08-06 22:08 UTC, vitorrafael commented on src/core/customers/exceptions/NonexistentCustomerError.js
> +  }
Conforme conversamos, aqui pode ser apenas `cpf` sem destruturação.

2024-08-07 23:00 UTC, anadezuo commented on src/adapters/database/SequelizeCustomerRepository.js
> +  }
Ah obrigada Vitor :pray: Vou aplicar

2024-08-07 23:05 UTC, anadezuo commented on src/adapters/database/FakeCustomerRepository.js
> +    if (!dbCustomer || dbCustomer?.length === 0) return undefined;
No momento que faço create, eu verifico se o cliente já foi inserido.
Caso o cliente não tenho inserido, o dbCustomer volta do sequelize como um array vazio.
E array vazio no if ! é retornado falso, pois o array vazio não é um valor falso, e assim tenta realizar a instância do objeto vazio e dá problema.

2024-08-07 23:37 UTC, anadezuo commented on src/adapters/database/SequelizeCustomerRepository.js
> +    if (!dbCustomer || dbCustomer?.length === 0) return undefined;
No momento que faço create, eu verifico se o cliente já foi inserido.
Caso o cliente não tenho inserido, o dbCustomer volta do sequelize como um array vazio.
E array vazio no if ! é retornado falso, pois o array vazio não é um valor falso, e assim tenta realizar a instância do objeto vazio e dá problema.

2024-08-08 00:08 UTC, anadezuo commented on src/adapters/database/FakeCustomerRepository.js
> +    if (!dbCustomer || dbCustomer?.length === 0) return undefined;
Como estava retornando uma lista antes, acabava chegando um array vazio. :face_exhaling:

2024-08-08 13:31 UTC, vitorrafael approved these changes
LGTM! 🚀

2024-08-08 13:34 UTC, merged